title: Araldika
subtitle: Armory and Ordinary of Malta
email: jh@jameshoward.us
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
port: 4004

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-inline-svg

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

paginate: 6
paginate_path: "/news/page/:num/"

svg:
  optimize: true

collections:
  pages:
    output: true
    permalink: /:slug
  posts:
    output: true
    permalink: /news/:year/:month/:day/:slug
    type: "post"
  armorial:
    output: true
    permalink: /armorial/:slug
    type: "arms"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "armorial"
    values:
      layout: "arms"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - share/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
